kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# Applies these network rules to the main control-plane node
- role: control-plane
  # Forwards port from your host machine (your PC) into the K8s node container
  extraPortMappings:
  # Port inside the K8s node container (where Traefik NodePort will listen)
  - containerPort: 30080
    # Port on your host PC (allows standard http:// requests without port in URL)
    hostPort: 80
    # Binds strictly to localhost
    listenAddress: "127.0.0.1"
