apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: k8squest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /  # ✅ Correct endpoint - nginx serves index page at /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
